(defconst kant-heading 
  '((
     "Elucidation"
     "Observation"
     "Introductory"
     "Of Experience "
     "Determining Ground"
     "The difference between "
     "The Human Intellect"
     "Of Logic in General"
     "Of Ideas in General"
     "Phenomenal Existences"
     "Analytic of Principles"
     "Of Transcendental Logic"
     "Analytic of Conceptions"
     "Of Transcendental Ideas"
     "Of the Ideal in General"
     "Transcendental Deduction"
     "The Ideal of Pure Reason"
     "The Canon of Pure Reason"
     "Transcendental Deduction "
     "Systematic Representation"
     "Antithetic of Pure Reason"
     "Analytical and Synthetical"
     "The History of Pure Reason"
     "In an Unphilosophical State"
     "Determine the Possibility, "
     "United in one Consciousness"
     "The Antinomy of Pure Reason"
     "Of the Transcendental Ideal"
     "Pure and Empirical Knowledge"
     "System of Cosmological Ideas"
     "Of the Ground of the Division"
     "the Totality of the Deduction"
     "The Discipline of Pure Reason"
     "Idea of a Transcendental Logic"
     "System of Transcendental Ideas"
     "The Totality of the Dependence "
     "The Ultimate End of Pure Reason"
     "Objects of the Senses in general"
     "Of the Ideal of the Summum Bonum"
     "The Architectonic of Pure Reason"
     "The Conceptions contained therein"
     "Of the Paralogisms of Pure Reason"
     "Cosmical Events from their Causes"
     "Transcendental Doctrine of Method"
     "Of Opinion, Knowledge, and Belief"
     "The Logical Form of all Judgements"
     "Objects into Phenomena and Noumena"
     "Transcendental Idealism as the Key"
     "Relation to the Cosmological Ideas"
     "Solution of the Cosmological Idea "
     "Transcendental Doctrine of Elements"
     "Of the Possibility of a Conjunction"
     "Regulative Principle of Pure Reason"
     "The Universal Problem of Pure Reason"
     "The Objective Unity of Apperception "
     "The universally possible employment "
     "Of the Difference Between Judgements "
     "In all Theoretical Sciences of Reason"
     "The Name of a Critique of Pure Reason"
     "Transcendental Analytic and Dialectic"
     "Of the Application of the Categories "
     "Of Transcendental Illusory Appearance"
     "Philosophy stands in need of a Science"
     "Conclusions from the above Conceptions"
     "The only legitimate use of the Category"
     "Of the Division of Transcendental Logic "
     "Principles, and Extent of Human Knowledge"
     "Idea and Division of a Particular Science"
     "Conclusion of the Transcendental Æsthetic"
     "All Pure Conceptions of the Understanding"
     "The pure Conceptions of the Understanding"
     "In Cognition, its Application to Objects "
     "Of the necessity imposed upon Pure Reason"
     "Proof of the Existence of a Supreme Being"
     "The Discipline of Pure Reason in Polemics"
     "Metaphysical Exposition of this Conception"
     "Metaphysical Exposition of this Conception"
     "General Remarks on Transcendental Æsthetic"
     "Conditions under which alone the manifold "
     "Presented in the four Transcendental Ideas"
     "Possession of Certain Cognitions “à priori”"
     "Conclusions from the foregoing Conceptions "
     "The manifold representations given by Sense"
     "The Solution of Pure Cosmological Dialectic"
     "The Discipline of Pure Reason in Hypothesis"
     "Of the Transcendental Clue to the Discovery "
     "Reason with regard to the Cosmological Ideas"
     "What Objective Unity of Self-consciousness is"
     "Critical Solution of the Cosmological Problem"
     "Of the Ultimate End of the Pure Use of Reason"
     "Synthetical Judgements contained as Principles"
     "Synthetical Principles of the Pure Understanding"
     "Of the Empirical Use of the Regulative Principle"
     "Of the Arguments employed by Speculative Reason "
     "Of the Logical Use of the Understanding in General"
     "System of all Principles of the Pure Understanding"
     "Sceptical Exposition of the Cosmological Problems "
     "Transcendental Exposition of the Conception of Time"
     "Of the Originally Synthetical Unity of Apperception"
     "Of the Impossibility of a Physico-Theological Proof"
     "The Discipline of Pure Reason in Relation to Proofs"
     "Transcendental Exposition of the Conception of Space"
     "Presenting a Solution of its Transcendental Problems"
     "All Sensuous Intuitions are subject to the Categories"
     "Of the Transcendental Faculty of judgement in General"
     "Of the Supreme Principle of all Analytical Judgements"
     "Of the Supreme Principle of all Synthetical Judgements"
     "Of the Interest of Reason in these Self-contradictions"
     "The Principle of the Synthetical Unity of Apperception "
     "Experience of the Pure Conceptions of the Understanding"
     "The Discipline of Pure Reason in the Sphere of Dogmatism"
     "Of the Logical Function of the Understanding in Judgements"
     "Of the Principles of a Transcendental Deduction in general"
     "The highest Principle of all exercise of the Understanding"
     "The Totality of the Division of a Whole given in Intuition"
     "Of the Pure Conceptions of the Understanding, or Categories"
     "Of the Division of General Logic into Analytic and Dialectic"
     "Of the Deduction of the Pure Conception of the Understanding"
     "Transition to the Transcendental Deduction of the Categories"
     "The Totality of the Composition of Phenomena in the Universe"
     "Result of this Deduction of the Conceptions of the Understanding"
     "Of Pure Reason as the Seat of Transcendental Illusory Appearance"
     "Of the Schematism at of the Pure Conceptions of the Understanding"
     "Appendix Of the Regulative Employment of the Ideas of Pure Reason"
     "Of the Impossibility of an Ontological Proof of the Existence of God"
     "Of the Impossibility of a Cosmological Proof of the Existence of God"
     "Critique of all Theology based upon Speculative Principles of Reason")))

(provide 'kant-heading-dict-EN)
